 # https://gecgithub01.walmart.com/mobile-platform/github-app-monolith
enabled_features:
  - autolabeler
  - bot-pr-merge
  - semantic-pull-requests
  - stalebot
  - merge-queue
  - stale-branch-bot
  - sync-base-branch
merge_user: pranaygupta5
add_pr_label: allowRetry
sync_base_branch_on_changed_files_intersect:
  - "^libs\/.*\/src\/"
  - "^apps\/.*\/app\/"

